engine = "mysql"
engine_varsion ="8.0.27"
db_family ="mysql8.0"
db_major_engine_version ="8.0"
instance_type ="db.t3.micro"
allocated_storage =20
max_allocated_storage =100
db_name ="avnish"
username ="avnish1"
performance_insights_retention_period=7